spring:
  application:
    #服务名称
    name: hwa-eureka-client
#主机名
eureka:
  client:
    #eureka服务地址
    #注明自己的服务注册中心的地址，与Eureka Server中的配置application.yml相对应
    service-url:
      defaultZone: http://localhost:1116/eureka/